
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xKral_Tr
 */
public class CalisanEkleEkrani extends javax.swing.JDialog {
    public int OldposX;
    public int OldposY;
    DefaultTableModel model;
    VeriTabaniIslemleri.CalisanVeriTabaniIslemleri islemler = new VeriTabaniIslemleri(). new CalisanVeriTabaniIslemleri();
    
    
    
    
    /**
     * Creates new form CalisanEkleEkrani
     */
    public CalisanEkleEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) calisanTable.getModel();
        calisanGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uyariCalisan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        email_alani = new javax.swing.JTextField();
        tel_alani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        maas_alani = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calisanTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        dinamikArama2 = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dept_alani = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        kButton2 = new keeptoo.KButton();
        yikmaSilB = new keeptoo.KButton();
        yikmaEkleB = new keeptoo.KButton();
        yikmaYedekB = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);

        uyariCalisan.setForeground(new java.awt.Color(255, 0, 51));

        jPanel1.setBackground(java.awt.Color.darkGray);

        tel_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_alaniActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ad");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Çalıştığı Firma");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefon Numarası");

        calisanTable.setBackground(new java.awt.Color(153, 153, 153));
        calisanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ad", "Soyad", "Çalıştığı Firma", "E-mail", "Telefon Numarası", "Maaş"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calisanTable.setSelectionBackground(java.awt.Color.darkGray);
        calisanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calisanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(calisanTable);
        if (calisanTable.getColumnModel().getColumnCount() > 0) {
            calisanTable.getColumnModel().getColumn(0).setResizable(false);
            calisanTable.getColumnModel().getColumn(1).setResizable(false);
            calisanTable.getColumnModel().getColumn(2).setResizable(false);
            calisanTable.getColumnModel().getColumn(3).setResizable(false);
            calisanTable.getColumnModel().getColumn(4).setResizable(false);
            calisanTable.getColumnModel().getColumn(5).setResizable(false);
            calisanTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Maaş");

        dinamikArama2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinamikArama2KeyReleased(evt);
            }
        });

        jLabel7.setText("Arama");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));

        kButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-25.png"))); // NOI18N
        kButton2.setkEndColor(new java.awt.Color(0, 255, 255));
        kButton2.setkFillButton(false);
        kButton2.setkHoverEndColor(new java.awt.Color(51, 255, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 255, 51));
        kButton2.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        kButton2.setkStartColor(java.awt.Color.darkGray);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        yikmaSilB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-25.png"))); // NOI18N
        yikmaSilB.setkEndColor(new java.awt.Color(0, 255, 255));
        yikmaSilB.setkFillButton(false);
        yikmaSilB.setkHoverEndColor(new java.awt.Color(51, 255, 51));
        yikmaSilB.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        yikmaSilB.setkSelectedColor(new java.awt.Color(0, 204, 204));
        yikmaSilB.setkStartColor(java.awt.Color.darkGray);
        yikmaSilB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yikmaSilBActionPerformed(evt);
            }
        });

        yikmaEkleB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-25.png"))); // NOI18N
        yikmaEkleB.setkEndColor(new java.awt.Color(0, 255, 255));
        yikmaEkleB.setkFillButton(false);
        yikmaEkleB.setkHoverEndColor(new java.awt.Color(51, 255, 51));
        yikmaEkleB.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        yikmaEkleB.setkStartColor(java.awt.Color.darkGray);
        yikmaEkleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yikmaEkleBActionPerformed(evt);
            }
        });

        yikmaYedekB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-25.png"))); // NOI18N
        yikmaYedekB.setkEndColor(new java.awt.Color(0, 255, 255));
        yikmaYedekB.setkFillButton(false);
        yikmaYedekB.setkHoverEndColor(new java.awt.Color(51, 255, 51));
        yikmaYedekB.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        yikmaYedekB.setkPressedColor(java.awt.Color.darkGray);
        yikmaYedekB.setkStartColor(java.awt.Color.darkGray);
        yikmaYedekB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yikmaYedekBActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        kButton1.setForeground(new java.awt.Color(0, 255, 153));
        kButton1.setText("X");
        kButton1.setkBackGroundColor(java.awt.Color.darkGray);
        kButton1.setkEndColor(java.awt.Color.darkGray);
        kButton1.setkForeGround(new java.awt.Color(0, 153, 153));
        kButton1.setkHoverEndColor(java.awt.Color.darkGray);
        kButton1.setkHoverForeGround(new java.awt.Color(255, 0, 51));
        kButton1.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        kButton1.setkPressedColor(new java.awt.Color(153, 153, 153));
        kButton1.setkSelectedColor(new java.awt.Color(153, 153, 153));
        kButton1.setkStartColor(java.awt.Color.darkGray);
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email_alani)
                            .addComponent(dept_alani)
                            .addComponent(soyad_alani)
                            .addComponent(ad_alani)
                            .addComponent(tel_alani)
                            .addComponent(maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(yikmaEkleB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(yikmaSilB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(yikmaYedekB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(59, 59, 59)
                        .addComponent(dinamikArama2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(508, 508, 508))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dinamikArama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dept_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(email_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tel_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yikmaSilB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yikmaEkleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yikmaYedekB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(uyariCalisan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(uyariCalisan))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    

    

    
    
    private void tel_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_alaniActionPerformed

    private void calisanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calisanTableMouseClicked
        int selectedrow = calisanTable.getSelectedRow();
        
        ad_alani.setText(model.getValueAt(selectedrow, 1).toString());
        soyad_alani.setText(model.getValueAt(selectedrow, 2).toString());
        dept_alani.setText(model.getValueAt(selectedrow, 3).toString());
        email_alani.setText(model.getValueAt(selectedrow, 4).toString());
        tel_alani.setText(model.getValueAt(selectedrow, 5).toString());
        maas_alani.setText(model.getValueAt(selectedrow, 6).toString());
    }//GEN-LAST:event_calisanTableMouseClicked
    
    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        calisanTable.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    
    private void dinamikArama2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinamikArama2KeyReleased
        String ara = dinamikArama2.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_dinamikArama2KeyReleased

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed

        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String dept = dept_alani.getText();
        String email = email_alani.getText();
        int telNo = Integer.valueOf(tel_alani.getText());     
        int maas = Integer.valueOf(maas_alani.getText());
         
        int selectedrow = calisanTable.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount() == 0){
                
                uyariCalisan.setText("Calisanlar Tablosu Boş!");
                
            }
            else{
                
                uyariCalisan.setText("Lütfen Güncellenecek Bir Çalışan Seçiniz!");
                
            }
            
        }
        else{
            
            int id = (int)model.getValueAt(selectedrow, 0);
            islemler.calisanGuncelle(id,ad,soyad,dept,email,telNo,maas);
            calisanGoruntule();
            
            uyariCalisan.setText("Çalışan Başarıyla Güncellendi!");
            
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void yikmaSilBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yikmaSilBActionPerformed

        uyariCalisan.setText("");
        
        int selectedrow = calisanTable.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount() ==0)
            {
                
                uyariCalisan.setText("Calisanlar Tablosu Boş!");
                
            }
            else{
                
                uyariCalisan.setText("Lütfen Güncellenecek Bir Çalışan Seçiniz!");
                
            }
            
        }
        else{
            
            int id = (int)model.getValueAt(selectedrow, 0);
            islemler.calisanSil(id);
            calisanGoruntule();
            
            uyariCalisan.setText("Çalışan Başarıyla Silindi!");
            
        }
    }//GEN-LAST:event_yikmaSilBActionPerformed

    private void yikmaEkleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yikmaEkleBActionPerformed

        uyariCalisan.setText("");
        
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String dept = dept_alani.getText();
        String email = email_alani.getText();
        int telNo = Integer.valueOf(tel_alani.getText());        
        int maas = Integer.valueOf(maas_alani.getText());
        
        islemler.calisanEkle(ad,soyad,dept,email,telNo,maas);
        if(islemler.bayrak == 0){
            
            jLabel9.setText("Böyle bir firma bulunamıyor!");
            
        }
        
        calisanGoruntule();
        
        uyariCalisan.setText("Yeni Çalışan Başarıyla Eklendi...");
    }//GEN-LAST:event_yikmaEkleBActionPerformed

    private void yikmaYedekBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yikmaYedekBActionPerformed
        File file = new File("CalisanlarYedek.txt");//proje içinde text.txt adında bir txt oluşturun.
        
        ArrayList<Calisan> calisanlar = new ArrayList<Calisan>();
        
        calisanlar = islemler.calisanlariGetir();
        
        if(calisanlar != null){
                        
             try(BufferedWriter br = new BufferedWriter(new FileWriter(file))){
                            for(Calisan calisan : calisanlar){
                            br.write(calisan.getAd() + " " + calisan.getSoyad() + " " + calisan.getDepartman()+ " " + calisan.getEmail() + " " + calisan.getTelNo() + " " + calisan.getMaas() );
                            br.newLine();
                            }
                        }

                        catch (IOException e) {
                            System.out.println("Unable to read file " +file.toString());
                    }                          
        }      
    }//GEN-LAST:event_yikmaYedekBActionPerformed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        int posX = evt.getXOnScreen();
        int posY = evt.getYOnScreen();
        this.setLocation(posX - OldposX, posY - OldposY);
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        OldposX = evt.getX();
        OldposY = evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_kButton1ActionPerformed

    public void calisanGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<Calisan> calisanlar = new ArrayList<Calisan>();
        
        calisanlar = islemler.calisanlariGetir();
        
        if(calisanlar != null){
            
            for(Calisan calisan : calisanlar){
                
                Object[] eklenecek = {calisan.getId(),calisan.getAd(),calisan.getSoyad(),calisan.getDepartman(),calisan.getEmail(),calisan.getTelNo(),calisan.getMaas()};
                model.addRow(eklenecek);
                
            }
            
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalisanEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalisanEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalisanEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalisanEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalisanEkleEkrani dialog = new CalisanEkleEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTable calisanTable;
    private javax.swing.JTextField dept_alani;
    private javax.swing.JTextField dinamikArama2;
    private javax.swing.JTextField email_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private javax.swing.JTextField maas_alani;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField tel_alani;
    private javax.swing.JLabel uyariCalisan;
    private keeptoo.KButton yikmaEkleB;
    private keeptoo.KButton yikmaSilB;
    private keeptoo.KButton yikmaYedekB;
    // End of variables declaration//GEN-END:variables
}
