
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xKral_Tr
 */
public class yikilcakEvEkrani extends javax.swing.JDialog {
    
    public int OldposX;
    public int OldposY;
    DefaultTableModel model;
    VeriTabaniIslemleri.yikilcakEvVeriTabaniIslemleri islemler = new VeriTabaniIslemleri(). new yikilcakEvVeriTabaniIslemleri();
    
    /**
     * Creates new form yikilcakEvEkrani
     */
    public yikilcakEvEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(100,100);
        model = (DefaultTableModel) yikilcakEvT.getModel();
        yikilcakEvGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ilce_alani = new javax.swing.JTextField();
        aptNo_alani = new javax.swing.JTextField();
        aptAd_alani = new javax.swing.JTextField();
        sokak_alani = new javax.swing.JTextField();
        mah_alani = new javax.swing.JTextField();
        il_alani = new javax.swing.JTextField();
        mkare_alani = new javax.swing.JTextField();
        firmAdi_alani = new javax.swing.JTextField();
        tarih_alani = new javax.swing.JTextField();
        maliyet_alani = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        yikilcakEvT = new javax.swing.JTable();
        jSeparator10 = new javax.swing.JSeparator();
        yikmaYedekB = new keeptoo.KButton();
        yikmaEkleB = new keeptoo.KButton();
        yikmaSilB = new keeptoo.KButton();
        yikilcakEKranCikis = new keeptoo.KButton();
        jLabel11 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(java.awt.Color.darkGray);

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("İl");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("İlçe");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mahalle");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadde/Sokak");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bina Adı");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bina No");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Metrekare");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Yikicak Firma");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Yikma Maliyeti");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Yikma Suresi");

        ilce_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ilce_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilce_alaniActionPerformed(evt);
            }
        });

        aptNo_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aptNo_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptNo_alaniActionPerformed(evt);
            }
        });

        aptAd_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sokak_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mah_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        il_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mkare_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        firmAdi_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tarih_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        maliyet_alani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Arama");

        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        yikilcakEvT.setBackground(new java.awt.Color(153, 153, 153));
        yikilcakEvT.setForeground(new java.awt.Color(255, 255, 255));
        yikilcakEvT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İd", "İl", "İlçe", "Mahalle", "Cadde/sokak", "Apartman Adı", "Apartman No", "Metrekare", "Yıkan Firma", "Yıkma Maliyeti", "Bitiş Günü"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        yikilcakEvT.setGridColor(new java.awt.Color(255, 255, 255));
        yikilcakEvT.setSelectionBackground(java.awt.Color.darkGray);
        yikilcakEvT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yikilcakEvTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(yikilcakEvT);

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));

        yikmaYedekB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-25.png"))); // NOI18N
        yikmaYedekB.setkFillButton(false);
        yikmaYedekB.setkHoverForeGround(new java.awt.Color(0, 255, 51));
        yikmaYedekB.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        yikmaYedekB.setkPressedColor(java.awt.Color.darkGray);
        yikmaYedekB.setkStartColor(java.awt.Color.darkGray);
        yikmaYedekB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yikmaYedekBActionPerformed(evt);
            }
        });

        yikmaEkleB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-25.png"))); // NOI18N
        yikmaEkleB.setkFillButton(false);
        yikmaEkleB.setkHoverForeGround(new java.awt.Color(0, 255, 51));
        yikmaEkleB.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        yikmaEkleB.setkStartColor(java.awt.Color.darkGray);
        yikmaEkleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yikmaEkleBActionPerformed(evt);
            }
        });

        yikmaSilB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-25.png"))); // NOI18N
        yikmaSilB.setkFillButton(false);
        yikmaSilB.setkHoverForeGround(new java.awt.Color(0, 255, 51));
        yikmaSilB.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        yikmaSilB.setkStartColor(java.awt.Color.darkGray);
        yikmaSilB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yikmaSilBActionPerformed(evt);
            }
        });

        yikilcakEKranCikis.setForeground(new java.awt.Color(0, 255, 153));
        yikilcakEKranCikis.setText("X");
        yikilcakEKranCikis.setkBackGroundColor(java.awt.Color.darkGray);
        yikilcakEKranCikis.setkEndColor(java.awt.Color.darkGray);
        yikilcakEKranCikis.setkForeGround(new java.awt.Color(0, 153, 153));
        yikilcakEKranCikis.setkHoverEndColor(java.awt.Color.darkGray);
        yikilcakEKranCikis.setkHoverForeGround(new java.awt.Color(255, 0, 51));
        yikilcakEKranCikis.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        yikilcakEKranCikis.setkPressedColor(new java.awt.Color(153, 153, 153));
        yikilcakEKranCikis.setkSelectedColor(new java.awt.Color(153, 153, 153));
        yikilcakEKranCikis.setkStartColor(java.awt.Color.darkGray);
        yikilcakEKranCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yikilcakEKranCikisActionPerformed(evt);
            }
        });

        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        kButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-25.png"))); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(0, 255, 255));
        kButton1.setkFillButton(false);
        kButton1.setkHoverEndColor(new java.awt.Color(0, 255, 51));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 255, 51));
        kButton1.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        kButton1.setkStartColor(java.awt.Color.darkGray);
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator2)
                                        .addComponent(jSeparator1)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jSeparator8)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel9)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addComponent(jLabel10))
                                                    .addGap(67, 67, 67)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ilce_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(maliyet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firmAdi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(mkare_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(aptNo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(aptAd_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(sokak_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(mah_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(il_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jSeparator9))))))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(yikmaSilB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(yikmaEkleB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(yikmaYedekB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(36, 36, 36)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
                                    .addComponent(jSeparator10))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yikilcakEKranCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yikilcakEKranCikis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(il_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator10))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ilce_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mah_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sokak_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(aptAd_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(aptNo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(mkare_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(firmAdi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(maliyet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addComponent(yikmaEkleB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yikmaSilB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yikmaYedekB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ilce_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilce_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ilce_alaniActionPerformed

    private void aptNo_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptNo_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptNo_alaniActionPerformed
    
    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        yikilcakEvT.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    
    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        String ara = jTextField2.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_jTextField2KeyReleased

    private void yikilcakEKranCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yikilcakEKranCikisActionPerformed
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_yikilcakEKranCikisActionPerformed

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
        int posX = evt.getXOnScreen();
        int posY = evt.getYOnScreen();
        this.setLocation(posX - OldposX, posY - OldposY);
    }//GEN-LAST:event_jLabel11MouseDragged

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        OldposX = evt.getX();
        OldposY = evt.getY();
    }//GEN-LAST:event_jLabel11MousePressed

    private void yikmaSilBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yikmaSilBActionPerformed
       
        int selectedrow = yikilcakEvT.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount() ==0)
            {
                               
                //JOptionPane.showMessageDialog(this, "Yıkılcak Ev Tablosu Boş!");
                
            }
            else{
                
                
                //JOptionPane.showMessageDialog(this, "Lütfen Güncellenecek Bir Yıkılcak Ev Seçiniz!");
            }
            
        }
        else{
            
            int id = (int)model.getValueAt(selectedrow, 0);
            islemler.yikilcakEvSil(id);
            yikilcakEvGoruntule();
            
            //JOptionPane.showMessageDialog(this, "Yıkılcak Ev Başarıyla Silindi!");
            
            
        }
    }//GEN-LAST:event_yikmaSilBActionPerformed

    private void yikilcakEvTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yikilcakEvTMouseClicked
        
        int selectedrow = yikilcakEvT.getSelectedRow();
        
        il_alani.setText(model.getValueAt(selectedrow, 1).toString());
        ilce_alani.setText(model.getValueAt(selectedrow, 2).toString());
        mah_alani.setText(model.getValueAt(selectedrow, 3).toString());
        sokak_alani.setText(model.getValueAt(selectedrow, 4).toString());
        aptAd_alani.setText(model.getValueAt(selectedrow, 5).toString());
        aptNo_alani.setText(model.getValueAt(selectedrow, 6).toString());
        mkare_alani.setText(model.getValueAt(selectedrow, 7).toString());       
        firmAdi_alani.setText(model.getValueAt(selectedrow, 8).toString());
        maliyet_alani.setText(model.getValueAt(selectedrow, 9).toString());
        tarih_alani.setText(model.getValueAt(selectedrow, 10).toString());
        
    }//GEN-LAST:event_yikilcakEvTMouseClicked

    private void yikmaEkleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yikmaEkleBActionPerformed
        
        String il = il_alani.getText();
        String ilce = ilce_alani.getText();
        String mahalle = mah_alani.getText();
        String cadde = sokak_alani.getText();
        String aptAd = aptAd_alani.getText();
        int aptNo = Integer.valueOf(aptNo_alani.getText());
        int mKare = Integer.valueOf(mkare_alani.getText());
        String yikicakFirma = firmAdi_alani.getText();
        int yikmaMaliyet = Integer.valueOf(maliyet_alani.getText());
        String tarih = tarih_alani.getText();
        
        islemler.yikilcakEvEkle(il, ilce, mahalle, cadde, aptAd, aptNo, mKare, yikicakFirma, yikmaMaliyet,tarih );
        
        if(islemler.bayrak2 ==0){
            jLabel13.setText("Böyle bir firma bulunmuyor");
            
        }
        
        yikilcakEvGoruntule();
        
        //JOptionPane.showMessageDialog(this, "Yıkılcak Ev Başarıyla Silindi!");
        
    }//GEN-LAST:event_yikmaEkleBActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        
        String il = il_alani.getText();
        String ilce = ilce_alani.getText();
        String mahalle = mah_alani.getText();
        String cadde = sokak_alani.getText();
        String aptAd = aptAd_alani.getText();
        int aptNo = Integer.valueOf(aptNo_alani.getText());
        int mKare = Integer.valueOf(mkare_alani.getText());
        String yikicakFirma = firmAdi_alani.getText();
        int yikmaMaliyet = Integer.valueOf(maliyet_alani.getText());
        String tarih = tarih_alani.getText();
        
        int selectedrow = yikilcakEvT.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount() == 0){
                
                //JOptionPane.showMessageDialog(this, "Yıkılcak Ev Tablosu Boş!");
                
            }
            else{
                
                //JOptionPane.showMessageDialog(this, "Lütfen Güncellenecek Bir Yıkılcak Ev Seçiniz!");
                
            }
            
        }
        else{
            
            int id = (int)model.getValueAt(selectedrow, 0);
            islemler.yikilcakEvGuncelle(id, il, ilce, mahalle, cadde, aptAd, aptNo, mKare, yikicakFirma, yikmaMaliyet, tarih);
            yikilcakEvGoruntule();
            
            //JOptionPane.showMessageDialog(this, "Yıkılcak Ev Başarıyla Silindi!");
            
        }
        
    }//GEN-LAST:event_kButton1ActionPerformed

    private void yikmaYedekBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yikmaYedekBActionPerformed
        File file = new File("YikilcakEvYedek.txt");//proje içinde text.txt adında bir txt oluşturun.
        
        ArrayList<yikilcakEv> evler = new ArrayList<yikilcakEv>();
        
        evler = islemler.yikilcakEvGetir();
        
        if(evler != null){
                        
             try(BufferedWriter br = new BufferedWriter(new FileWriter(file))){
                            for(yikilcakEv yEv : evler){
                            br.write(yEv.getIl() + " " + yEv.getIlce() + " " + yEv.getMahalle() + " " + yEv.getCadde() + " " + yEv.getAptAd() + " " + yEv.getAptNo() + " " + yEv.getArsaMKare() + " " + yEv.getYikicakFirma() + " " + yEv.getYikmaMaliyeti() + " " +  yEv.getYikmaSuresi() );
                            br.newLine();
                            }
                        }

                        catch (IOException e) {
                            System.out.println("Unable to read file " +file.toString());
                    }                          
        }
    }//GEN-LAST:event_yikmaYedekBActionPerformed
    
    public void yikilcakEvGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<yikilcakEv> evler = new ArrayList<yikilcakEv>();
        
        evler = islemler.yikilcakEvGetir();
        
        if(evler != null){
            
            for(yikilcakEv yEv : evler){
                
                Object[] eklenecek = {yEv.getId(),yEv.getIl(),yEv.getIlce(),yEv.getMahalle(),yEv.getCadde(),yEv.getAptAd(),yEv.getAptNo(),yEv.getArsaMKare(),yEv.getYikicakFirma(),yEv.getYikmaMaliyeti(),yEv.getYikmaSuresi()};
                model.addRow(eklenecek);
                
            }
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yikilcakEvEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yikilcakEvEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yikilcakEvEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yikilcakEvEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                yikilcakEvEkrani dialog = new yikilcakEvEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aptAd_alani;
    private javax.swing.JTextField aptNo_alani;
    private javax.swing.JTextField firmAdi_alani;
    private javax.swing.JTextField il_alani;
    private javax.swing.JTextField ilce_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private keeptoo.KButton kButton1;
    private javax.swing.JTextField mah_alani;
    private javax.swing.JTextField maliyet_alani;
    private javax.swing.JTextField mkare_alani;
    private javax.swing.JTextField sokak_alani;
    private javax.swing.JTextField tarih_alani;
    private keeptoo.KButton yikilcakEKranCikis;
    private javax.swing.JTable yikilcakEvT;
    private keeptoo.KButton yikmaEkleB;
    private keeptoo.KButton yikmaSilB;
    private keeptoo.KButton yikmaYedekB;
    // End of variables declaration//GEN-END:variables
}
